### ISSUE TITLE
 nested-sampling

### ISSUE THREAD

**Issue by Lexo-G** [BEAST2-Dev/nested-sampling#10]
I'm trying to run [Nested Sampling](https://github.com/BEAST2-Dev/nested-sampling) using [this file](https://drive.google.com/drive/folders/1jh5h1KCxlRFkpeCF39r0pTu0fT8BAzKr?usp=sharing) that is set to particleCount="5" and I'm getting large positive marginal likelihoods. At particleCount="1" marginal likelihoods seem to be normal (i.e. negative). Pretty much the same applies to my other data: 1 particle generates negative values, while > 1 particles generate overly large positive values. Does this mean that I need to stick with small particle counts? What if I need to increase the particle number to meet requirements suggested in the online manual of this package?

I appreciate your help,
Lexo

**Comment by rbouckaert** [comment]
There appear to be improper priors in the XML: priors that do not integrate to 1, like uniform priors with infinite upper or lower bounds and 1/X priors. You might have been lucky with 1 particle, but with more than 1 a sample from the prior can make parameters escape to extremely large or small values, resulting in numerical issues.

Positive marginal likelihoods suggest some parameter values became extreme resulting in numerical issues.

Replace the improper priors with proper ones and things should run without this problem.

**Comment by Lexo-G** [comment]
Thanks a lot.
