### ISSUE TITLE
Guidelines for setting up a run with nested sampling?

### ISSUE THREAD

**Issue by richelbilderbeek** [BEAST2-Dev/nested-sampling#2]
Thanks again to the BEAST2 devs (I guess mostly @rbouckaert?) for this nice piece of work!

What I'd like to see documented, are some guidelines how to set up a nested sampling run.

Questions that I have:

 * Is there a recommended minimum effective sampling size of the marginal likelihood 
   estimation? Or does the estimation error given suffice in knowing how strong the inference is?
 * If there a recommended minimum effective sampling size of the marginal likelihood 
   estimation, which value?
 * How many particles should one use?
 * What should the relationship be, between chainlength and sub-chainlength?

Perhaps most of these are unknowns...

Thanks, @richelbilderbeek

**Comment by rbouckaert** [comment]
ESS is a useful measure of convergence for MCMC, but does not apply to the marginal likelihood (ML) estimate in nested sampling (NS). For NS, the ML estimate comes with an estimate of its standard deviation (SD) of the *log* ML. To compare two models, say M1 and M2, the difference of log MLs is the Bayes factor (BF). If the SDs are too large, the BF cannot be trusted.

Estimating ESS of posterior samples from NS is an open research question. There is an upper bound, which is the number of samples in the posterior log files, but depending on among other things operator weights and MCMC sample efficiency, it is not clear how far off that bound is.

SD is estimated as sqrt(H/N) where H the information (estimated during NS run) and N the number of particles. So the SD decreases with sqrt(N). If you run with a small number of particles and the SD is too large to obtain reliable BFs, you can specify a target SD that would allow you to get a reliable estimate of the BFs, and run with N = H/SD^2 particles (take the ceil to get an integer value for N).

The chainlength is only used as upper bound on the number of iterations of the NS analysis, so if set sufficiently high will be ignored (NS stops automatically after 2*H*N steps, unless the information changes more than epsilon, and 2*H*N tends to be much lower than chainlength). Subchainlength is the length of the MCMC chain for a single NS step.

Hope this clarifies things,

Remco

**Comment by richelbilderbeek** [comment]
Cool, I saw you work at the Wiki, very helpful!

Keep up the good work :+1:
